version: "3"
 
services:
  microService:
    image: zdfy_docker:1.0
    restart: always
    container_name: zdfy
    ports:
      - "8080:8080"
    volumes:
      - /app/microService:/data
    networks: 
      - fan_net 
    depends_on: 
      - redis
      - mysql
      - clickhouse
      - minio
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - /app/redis/redis.conf:/etc/redis/redis.conf
      - /app/redis/data:/data
    networks: 
      - fan_net
    command: redis-server /etc/redis/redis.conf
 
  mysql:
    image: mysql/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'db2021'
      MYSQL_USER: 'ffxx'
      MYSQL_PASSWORD: 'ffxx123'
    ports:
       - "3306:3306"
    volumes:
       - /app/mysql/db:/var/lib/mysql
       - /app/mysql/conf/my.cnf:/etc/my.cnf
       - /app/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - fan_net
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问
  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    environment:
      CLICKHOUSE_DEFAULT_PASSWORD: '123456'
      CLICKHOUSE_ALLOW_EMPTY_PASSWORD: 'no'
      CLICKHOUSE_DATABASE: 'default'
      CLICKHOUSE_USER: 'default'
      CLICKHOUSE_PASSWORD: '123456'
    ports:
       - "19000:9000"
       - "8123:8123"
    volumes:
       - /app/clickhouse/db:/var/lib/clickhouse
       - /app/clickhouse/log:/var/log/clickhouse-server/
    networks:
      - fan_net

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: 'adminminio'
      MINIO_ROOT_PASSWORD: 'adminminio'
    ports:
      - "9080:9000"
      - "9090:9090"
    volumes:
      - /install/minio/data:/data
      - /install/minio/config:/root/.minio \
    networks: 
      - fan_net
    command: server /data --console-address ":9090" --address ":9000"
networks: 
   fan_net: 
 

